### ISSUE TITLE
enabling linting, error output on file save

### ISSUE THREAD

**Issue by mattiLeBlanc** [pbastowski/meteor-typescript#3]
Hi,

I noticed when I save a TS File, it is being rebuild but I am not getting any feedback on any errors during the compiling. So I only notice it when for example a subscription doesn't load.

Is that a setting in the tsconfig.json?

```
{
    "filesGlob": [
        "./typings/**/*.d.ts",
        "./server/**/*.ts",
        "./client/**/*.ts"
    ],
    "compilerOptions": {
        "module": "commonjs"
    },
    "compileOnSave": false,
    "buildOnSave": false
}
```

I tried setting compileOnSave to True but that didn't do it.

**Comment by pbastowski** [comment]
Matti, currently there is no support for tsconfig.json settings, except for the module setting. In the README I say this [here](https://github.com/pbastowski/meteor-typescript#the-old-way-without-systemjs).

> The only option read from this file is the module setting. Everything else is ignored currently.

Unfortunately, I don't have time right now to add this support.

**Comment by mattiLeBlanc** [comment]
Okay, no problem.
