### ISSUE TITLE
How to declare mongo collection in version 1.3

### ISSUE THREAD

**Issue by mattiLeBlanc** [pbastowski/meteor-typescript#4]
Hi,

Declaring a mongo collection triggers an error:

```
Invoices = new Mongo.Collection('invoices');
```

triggers

```
ReferenceError: Invoices is not defined
    at meteorInstall.lib.collections.invoices.ts (app/app.js:23:10)
    at fileEvaluate (packages/modules-runtime.js:158:9)
    at require (packages/modules-runtime.js:92:16)
```

This is after updating to Meteor 1.3 and also updating to pbastowski:typescript@1.3.0.
I am using system.js (as far as I know).

I understand the system.js way expects an import for modules but what to do with Meteor collections?

I am going to upgrade to angular2now tomorrow because my project is not working anymore because of the collection issue.

I just updated to Meteor 1.3 and then had to update typescript of course and had to go through all my code to add `export`. I was using commonJS before. Still something else doesnt work and unfortunately isn't well documented.  I am looking at a release in 2 weeks and I am running into Angular Meteor errors (after the rewrite a lot of stuff is going wrong, timing issues between angular and meteor) and things that break due to upgrades....not very happy with that. 
I am building a very nice product in Meteor for a commercial company and I can't have these uncertainties that every time I do a meteor update, something could break.

Any suggestions how to cope with that. Reason I ask is that I seems to have some trouble downgrading packages and/or meteor due to dependencies. So going back to the older working system doesn't seem an option.

**Comment by pbastowski** [comment]
Hi @mattiLeBlanc

SystemJS, as implemented in my package `pbastowski:systemjs`, does not work with Meteor 1.3. You need to use the new Meteor 1.3 `modules` package instead, which is included with my `pbastowski:typescript` package. However, before it all works, you need to first do `meteor remove pbastowski:systejs`. 

Update: Also, remove the `tsconfig.json` file, if you have it, as it is not required with my typescript@1.3.0 package and can interfere, if you set modules to "systemjs".

So, try the above and see if it helps. If not then please provide me a link to your repo or to a demo repo that replicates the issue and I will try to help you.

**Comment by mattiLeBlanc** [comment]
Ah okay. Will try that tomorrow morning. Will post result.
Cheers

**Comment by mattiLeBlanc** [comment]
Hi,

I don't think I can remove the whole tsconfig because it used for my IDE, isn't? Making sure the typings are loaded etc in Sublime or Visual Studio Code.

So I removed the compileOptions part of the tsconfig and now I am not getting System is not defined message anymore. Which is correct.
However, 

If I do not var my collection on the server side, I get an error message in my compiled server/app.js file (in the build folder)

```
"use strict";
ActivatedInvoices = new Mongo.Collection('activatedInvoices');

and the error is:
ReferenceError: ActivatedInvoices is not defined
```

where nodeJS tell my ActivatedInvoices is not defined, which is true. When I use let/var the error does not show, but then the invoices are not registered in Meteor (I can't find the mini mongo collection in my Chrome console) because I guess it is varred in the wrong scope.

I am reading the migration guide now, looking for a breaking change in Meteor 1.3 that might cause this but as far as I can see now I doing everything according to the book.

I am going to test it now in my small test repository which I can share with you in case I can't solve it.

I will keep you posted.

**Comment by mattiLeBlanc** [comment]
okay, 
only thing that makes this 

```
Invoices = new Mongo.Collection('invoices');
```

work for me is renaming the .ts file to .js :-)
I see what actually causes the issue: The TS compiler adds `"use strict";` to it and that is what is causing the error in my console.
If I add that to the JS file myself, I get the same error.
Am I doing something wrong with Meteor 1.3? (still reading the new guide)

**Comment by pbastowski** [comment]
Ok, I see the issue now. You can still use TypeScript, but you need to `export` your `Invoices` object from a module and then `import` it where you need it. To do that, you will need a separate file that contains just this code:

collections.js

``` js
export var Invoices = new Mongo.Collection('invoices');
```

then, import it into your front-end and back-end module(s), as required, like this:

``` js
import { Invoices } from "collections.js";
```

Does the above help you?

**Comment by mattiLeBlanc** [comment]
hah, that looks pretty complex, doesn't it. Or is it in line with how ES2016 functions?
My workaround was renaming the collection file to .js lol. But that is probably not a good approach.

So with regular Meteor developmnent (up to version 1.2) we would just declare the collection (like in the docs), with no import or export. I guess I can now import it somewhere toplevel so it works for client and server?

**Comment by pbastowski** [comment]
This is the new way of doing things with ES2015. All modules (files) are encapsulated in a closure and do not expose module scope variables or those declared without var on the global scope any more. You have to specifically export them in the defining module and import then in the consuming modules.

Strict mode is also the new default with ES2015. So, if you really need to put something on global then you specifically have to do `window.globalVar = 123` on the client and on the server side `process.globalVar = 123`. Although this is possible, you should instead export variables from modules, as describe above.

It seems like more work, but actually it gives you better control of what is visible where in your app, which reduces chances of bugs and helps prevent global scope pollution.

I would not try to import it at the "toplevel" and then try to make it global. Import it where you need it.

**Comment by mattiLeBlanc** [comment]
okay, crystal clear. Thanks!

**Comment by mattiLeBlanc** [comment]
actually not really that clear when I try to implement it.
If you look at the file structure of my demo app (which is probably featuring a older file structure used in meteor 1.0 to 1.2):
https://github.com/mattiLeBlanc/invoiceList

you see that I declare the collection in the LIB folder.
Then it is available for client and server.

Now as you suggest I used the export:

```
export var Invoices = new Mongo.Collection('invoices');
```

However,
I am not sure where to import it now. In my test app  I add the import to the publisher in the server folder (https://github.com/mattiLeBlanc/invoiceList/tree/master/server/publishers) but it says it doesnt know 'collections.js'

I also tried `import { Invoices } from "meteor/mongo";` in the publisher file in the server folder which doesn't throw an error but I have no idea if that is correct.

On the client in my controller where I subscribe, I can't use `import { Invoices } from "meteor/mongo";` so not sure how I can subscribe to my `invoice` subscription.

Can you have a quick look at the simple structure in my invoiceList test app and point out how to implement this correctly? 
I can't find it in the docs right now.

Also...does it mean we can't access the collection in the chrome console any more because it is only available in the angular scope of that controller?

**Comment by pbastowski** [comment]
Hi @mattiLeBlanc 

I created a repo https://github.com/pbastowski/meteor1.3-collection-import that illustrates how to create and import Mongo collections with Meteor 1.3.

Please have a look at it.

I had a look at your repo and, in summary, you must always import the Invoices object before you use it. You must import it on the server side also. But, you will have to move the "invoices.ts" file  to an `imports` folder for `import ... from ""` to work. You will also have to prepend `export var` to `Invoices = new Mongo...`. 

So, rather than change your whole app for you, I created the small repo, above, which shows the principles of how it works with Meteor 1.3.

**Comment by mattiLeBlanc** [comment]
Thank you very much.

You are using the extension .JS for the Typescript files. Shouldn't be TS
or is that not necessary anymore with the Typescript package you are using?

**Comment by pbastowski** [comment]
Good pickup. The file extensions in the README were supposed to be ".ts". I have fixed them all up now.

**Comment by mattiLeBlanc** [comment]
Great, thanks.
